name: CI/CD Lambdas & API Gateway
on:
  pull_request:
    branches:
      - develop  # PR a develop -> solo validaciones
  push:
    branches:
      - main     # Merge a main -> solo deploy
jobs:
  # ================== VALIDACIÓN ==================
  validate:
    if: github.event_name == 'pull_request' && github.base_ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - run: echo "La rama actual es ${{ github.ref_name }} - ${{ github.ref }}"
      - uses: actions/checkout@v3
      - run: npm install eslint -g
      - run: cd lambdas/obtener-productos && eslint . || true
      - run: cd lambdas/grabar-contacto && eslint . || true
      - run: npm test || true
      - uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - uses: github/codeql-action/analyze@v3
  # ================== DESPLIEGUE ==================
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Verificar secrets
        run: |
          if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ] || [ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then
            echo "Secrets no disponibles, cancelando deploy"
            exit 1
          fi
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1      
      # ---------------- Lambda: obtener-productos ----------------
      - name: Package Lambda obtener-productos
        run: |
          cd lambdas/obtener-productos
          zip -r ../../obtener-productos-package.zip .
      - name: Deploy Lambda obtener-productos
        run: |
          aws lambda update-function-code \
            --function-name obtener-productos \
            --zip-file fileb://obtener-productos-package.zip \
            --debug
      - name: Update API Gateway integration obtener-productos
        run: |
          aws apigatewayv2 update-integration \
            --api-id ${{ secrets.API_ID }} \
            --integration-id ${{ secrets.INTEGRATION_OBTENERPRODUCTO_ID }} \
            --integration-uri ${{ secrets.LAMBDA_OBTENERPRODUCTO_ARN }}
      # ---------------- Lambda: grabar-contacto ----------------
      - name: Package Lambda grabar-contacto
        run: |
          cd lambdas/grabar-contacto
          zip -r ../../grabar-contacto-package.zip .
      - name: Deploy Lambda grabar-contacto
        run: |
          aws lambda update-function-code \
            --function-name grabar-contacto \
            --zip-file fileb://grabar-contacto-package.zip \
            --debug
      - name: Update API Gateway integration grabar-contacto
        run: |
          aws apigatewayv2 update-integration \
            --api-id ${{ secrets.API_ID }} \
            --integration-id ${{ secrets.INTEGRATION_GRABARCONTACTO_ID }} \
            --integration-uri ${{ secrets.LAMBDA_GRABARCONTACTO_ARN }}