name: Deploy Lambdas & API Gateway
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    # ---------------- Lambda: obtener-productos ----------------
    - name: Package Lambda obtener-productos
      run: |
        cd lambdas/obtener-productos
        zip -r ../../obtener-productos-package.zip .
    - name: Deploy Lambda obtener-productos
      run: |
        aws lambda update-function-code \
          --function-name obtener-productos \
          --zip-file fileb://obtener-productos-package.zip
    - name: Update API Gateway integration obtener-productos
      run: |
        aws apigatewayv2 update-integration \
          --api-id ${{ secrets.API_ID }} \
          --integration-id ${{ secrets.INTEGRATION_OBTENERPRODUCTO_ID }} \
          --integration-uri ${{ secrets.LAMBDA_OBTENERPRODUCTO_ARN }}
    # ---------------- Lambda: grabar-contacto ----------------
    - name: Package Lambda grabar-contacto
      run: |
        cd lambdas/grabar-contacto
        zip -r ../../grabar-contacto-package.zip .
    - name: Deploy Lambda grabar-contacto
      run: |
        aws lambda update-function-code \
          --function-name grabar-contacto \
          --zip-file fileb://grabar-contacto-package.zip
    - name: Update API Gateway integration grabar-contacto
      run: |
        aws apigatewayv2 update-integration \
          --api-id ${{ secrets.API_ID }} \
          --integration-id ${{ secrets.INTEGRATION_GRABARCONTACTO_ID }} \
          --integration-uri ${{ secrets.LAMBDA_GRABARCONTACTO_ARN }}