name: CI/CD Lambdas & API Gateway
on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
permissions:
  contents: read
  pull-requests: write
  id-token: write
  actions: read
jobs:
  # ================== VALIDACIÓN EN PR ==================
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # --------- Linter ---------
      - name: Install ESLint
        run: npm install eslint -g
      - name: Lint Lambda obtener-productos
        run: |
          cd lambdas/obtener-productos
          eslint . || true  
      - name: Lint Lambda grabar-contacto
        run: |
          cd lambdas/grabar-contacto
          eslint . || true
      # --------- Unit tests ---------
      - name: Run Unit Tests
        run: npm test || true
      # --------- CodeQL (SAST) ---------
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
  # ================== DESPLIEGUE A MAIN ==================
  deploy:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    needs: validate
    permissions:
      contents: write        # necesario para push o acciones que modifiquen el repo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      # ---------------- Lambda: obtener-productos ----------------
      - name: Package Lambda obtener-productos
        run: |
          cd lambdas/obtener-productos
          zip -r ../../obtener-productos-package.zip .
      - name: Deploy Lambda obtener-productos
        run: |
          aws lambda update-function-code \
            --function-name obtener-productos \
            --zip-file fileb://obtener-productos-package.zip \
            --debug
      - name: Update API Gateway integration obtener-productos
        run: |
          aws apigatewayv2 update-integration \
            --api-id ${{ secrets.API_ID }} \
            --integration-id ${{ secrets.INTEGRATION_OBTENERPRODUCTO_ID }} \
            --integration-uri ${{ secrets.LAMBDA_OBTENERPRODUCTO_ARN }}
      # ---------------- Lambda: grabar-contacto ----------------
      - name: Package Lambda grabar-contacto
        run: |
          cd lambdas/grabar-contacto
          zip -r ../../grabar-contacto-package.zip .
      - name: Deploy Lambda grabar-contacto
        run: |
          aws lambda update-function-code \
            --function-name grabar-contacto \
            --zip-file fileb://grabar-contacto-package.zip \
            --debug
      - name: Update API Gateway integration grabar-contacto
        run: |
          aws apigatewayv2 update-integration \
            --api-id ${{ secrets.API_ID }} \
            --integration-id ${{ secrets.INTEGRATION_GRABARCONTACTO_ID }} \
            --integration-uri ${{ secrets.LAMBDA_GRABARCONTACTO_ARN }}