name: Deploy Lambdas on main
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # primer paso clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3
      # segundo paso configurar AWS CLI con secrets para no exponer el API Key.
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # tercer paso desplegar Lambda: obtener-productos
      - name: Deploy obtener-productos Lambda
        run: |
          cd lambdas/obtener-productos
          zip -r function.zip .
          aws lambda update-function-code \
            --function-name obtener-productos \
            --zip-file fileb://function.zip
          cd ../../
      # cuarto paso desplegar Lambda: grabar-contacto
      - name: Deploy grabar-contacto Lambda
        run: |
          cd lambdas/grabar-contacto
          zip -r function.zip .
          aws lambda update-function-code \
            --function-name grabar-contacto \
            --zip-file fileb://function.zip
          cd ../../
