name: ZAP Baseline Scan
on:
  pull_request:
    branches:
      - develop
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://api.tocupboard-dv.click/obtener-productos'
          rules_file_name: 'zap_rules.json'
          fail_on_error: 'true'
          cmd_options: >
            -config ssl.insecure=true
            -config replacer.full_list=[{"description":"API Key","enabled":true,"matchtype":"REQ_HEADER","matchregex":false,"matchstring":"x-api-key","replacement":"${{ secrets.AWS_API_KEY }}"}]
            -config globalexcludeurl.url_list=.*logout.*